// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0CwnOnA_zh9EaTI9DPe23osg7jXeUlU4',
    appId: '1:846615878928:web:5ae96af0b93f8998cad995',
    messagingSenderId: '846615878928',
    projectId: 'payment-manager-a3ef0',
    authDomain: 'payment-manager-a3ef0.firebaseapp.com',
    storageBucket: 'payment-manager-a3ef0.appspot.com',
    measurementId: 'G-GJNM30VPFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc6KwqTnLjT21dMAChI8RZpf90BiFSVT0',
    appId: '1:846615878928:android:491798342c34a6b4cad995',
    messagingSenderId: '846615878928',
    projectId: 'payment-manager-a3ef0',
    storageBucket: 'payment-manager-a3ef0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl0OKLIM6WGugtE1owWzYt-10zt4PSnNs',
    appId: '1:846615878928:ios:da38993497070c75cad995',
    messagingSenderId: '846615878928',
    projectId: 'payment-manager-a3ef0',
    storageBucket: 'payment-manager-a3ef0.appspot.com',
    iosBundleId: 'com.example.badgeTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl0OKLIM6WGugtE1owWzYt-10zt4PSnNs',
    appId: '1:846615878928:ios:e16be2f1a9d3eb35cad995',
    messagingSenderId: '846615878928',
    projectId: 'payment-manager-a3ef0',
    storageBucket: 'payment-manager-a3ef0.appspot.com',
    iosBundleId: 'com.example.badgeTask.RunnerTests',
  );
}
